matches:
  - { trigger: ';bb', replace: 'ğŸ‘' }
  - { trigger: ';book', replace: 'ğŸ“–' }
  - { trigger: ';bow', replace: 'ğŸ™‡' }
  - { trigger: ';check', replace: 'âœ…' }
  - { trigger: ';cloud', replace: 'ğŸ’­' }
  - { trigger: ';eye', replace: 'ğŸ‘€' }
  - { trigger: ';flow', replace: 'ğŸŒ€' }
  - { trigger: ';folder', replace: 'ğŸ“' }
  - { trigger: ';idea', replace: 'ğŸ’¡' }
  - { trigger: ';log', replace: 'ğŸ“œ' }
  - { trigger: ';memo', replace: 'ğŸ“' }
  - { trigger: ';ok', replace: 'ğŸ™†' }
  - { trigger: ';play', replace: 'â–¶ï¸' }
  - { trigger: ';pray', replace: 'ğŸ™' }
  - { trigger: ';stock', replace: 'ğŸ““' }
  - { trigger: ';tada', replace: 'ğŸ‰' }
  - { trigger: ';task', replace: 'â³' }
  - { trigger: ';think', replace: 'ğŸ¤”' }
  - { trigger: ';web', replace: 'ğŸŒ' }
  - { trigger: ';write', replace: 'âœï¸ ' }
  - { trigger: ';x', replace: 'âŒ' }
