matches:
  - { trigger: ';book', replace: 'ğŸ“–' }
  - { trigger: ';check', replace: 'âœ…' }
  - { trigger: ';flow', replace: 'ğŸŒ€' }
  - { trigger: ';folder', replace: 'ğŸ“' }
  - { trigger: ';idea', replace: 'ğŸ’¡' }
  - { trigger: ';log', replace: 'ğŸ“œ' }
  - { trigger: ';memo', replace: 'ğŸ“' }
  - { trigger: ';stock', replace: 'ğŸ““' }
  - { trigger: ';task', replace: 'â³' }
  - { trigger: ';think', replace: 'ğŸ¤”' }
  - { trigger: ';web', replace: 'ğŸŒ' }
  - { trigger: ';write', replace: 'âœï¸ ' }
  - { trigger: ';x', replace: 'âŒ' }
