filter_exec: Logseq

matches:
  - trigger: ';web'
    replace: 'ğŸŒ '

  - trigger: ';book'
    replace: 'ğŸ“– '

  - trigger: ';idea'
    replace: 'ğŸ’¡ '

  - trigger: ';memo'
    replace: 'ğŸ“ '

  - trigger: ';flow'
    replace: 'ğŸŒ€ '

  - trigger: ';x'
    replace: 'âŒ '

  - trigger: ';check'
    replace: 'âœ… '

  - trigger: ';log'
    replace: 'ğŸ“œ '
